using System;
using System.ComponentModel;
using System.Reflection;
using System.Collections.Generic;
using ExplorerTabUtility.Models;

namespace ExplorerTabUtility.Helpers;

/// <summary>
/// Localization keys and scope-dependent filtering for <see cref="HotKeyAction"/>.
/// <para>
/// Shared by the WPF and WinUI shells so the mapping is defined once. The shells only have to
/// render the returned strings with whatever control they use.
/// </para>
/// </summary>
public static class HotKeyActionCatalog
{
    private static readonly Dictionary<HotKeyAction, string> ActionKeys = new()
    {
        [HotKeyAction.Open] = "Action_Open",
        [HotKeyAction.Duplicate] = "Action_Duplicate",
        [HotKeyAction.ReopenClosed] = "Action_ReopenClosed",
        [HotKeyAction.TabSearch] = "Action_TabSearch",
        [HotKeyAction.NavigateBack] = "Action_NavigateBack",
        [HotKeyAction.NavigateUp] = "Action_NavigateUp",
        [HotKeyAction.NavigateForward] = "Action_NavigateForward",
        [HotKeyAction.SetTargetWindow] = "Action_SetTargetWindow",
        [HotKeyAction.ToggleWinHook] = "Action_ToggleWinHook",
        [HotKeyAction.ToggleReuseTabs] = "Action_ToggleReuseTabs",
        [HotKeyAction.ToggleVisibility] = "Action_ToggleVisibility",
        [HotKeyAction.DetachTab] = "Action_DetachTab",
        [HotKeyAction.SnapRight] = "Action_SnapRight",
        [HotKeyAction.SnapLeft] = "Action_SnapLeft",
        [HotKeyAction.SnapUp] = "Action_SnapUp",
        [HotKeyAction.SnapDown] = "Action_SnapDown",
    };

    private static readonly Dictionary<HotkeyScope, string> ScopeKeys = new()
    {
        [HotkeyScope.Global] = "ScopeGlobal",
        [HotkeyScope.FileExplorer] = "ScopeFileExplorer",
    };

    public static string GetActionDisplay(HotKeyAction action) =>
        ActionKeys.TryGetValue(action, out var key) ? LocalizationService.Get(key) : action.ToString();

    /// <summary>
    /// Which profile fields an action actually reads. The editor hides the rows that the selected
    /// action ignores, so the panel only ever shows settings that do something.
    /// </summary>
    /// <remarks>
    /// Mirrors <c>HookManager.HandleHotKeyProfileTriggeredAsync</c>: only <c>Open</c> passes
    /// <c>Path</c>, and only <c>Open</c> plus the four snap actions pass <c>Delay</c>.
    /// </remarks>
    public static bool UsesPath(HotKeyAction action) => action is HotKeyAction.Open;

    /// <summary>True when the action waits <c>Delay</c> milliseconds before running.</summary>
    public static bool UsesDelay(HotKeyAction action) =>
        action is HotKeyAction.Open
            or HotKeyAction.SnapRight or HotKeyAction.SnapLeft
            or HotKeyAction.SnapUp or HotKeyAction.SnapDown;

    /// <summary>
    /// True when the action honours <c>IsAsTab</c>. Only the three actions that bring a location up
    /// have a place to put a tab; the rest either act on an existing window or inject keystrokes.
    /// </summary>
    public static bool UsesAsTab(HotKeyAction action) =>
        action is HotKeyAction.Open or HotKeyAction.Duplicate or HotKeyAction.ReopenClosed;

    public static string GetScopeDisplay(HotkeyScope scope) =>
        ScopeKeys.TryGetValue(scope, out var key) ? LocalizationService.Get(key) : scope.ToString();

    /// <summary>
    /// Maps the legacy Chinese display names back to their action.
    /// <para>
    /// The WPF build auto-named new profiles with the enum's <c>[Description]</c> text, which was
    /// Chinese — so upgrading users are left with profiles literally called "显示/隐藏". The
    /// descriptions are still on the enum, so the reverse map is built from them at runtime rather
    /// than hard-coded a second time.
    /// </para>
    /// </summary>
    private static readonly Dictionary<string, HotKeyAction> LegacyChineseNames =
        BuildLegacyNameMap();

    private static Dictionary<string, HotKeyAction> BuildLegacyNameMap()
    {
        var map = new Dictionary<string, HotKeyAction>(StringComparer.Ordinal);

        foreach (var action in Enum.GetValues<HotKeyAction>())
        {
            var field = typeof(HotKeyAction).GetField(action.ToString());
            var description = field?.GetCustomAttribute<DescriptionAttribute>()?.Description;

            if (!string.IsNullOrWhiteSpace(description))
                map[description] = action;
        }

        return map;
    }

    /// <summary>
    /// Translates a legacy Chinese profile name to a short English one. Returns null when the name
    /// was not auto-generated by the old build (i.e. the user typed it, so it must be left alone).
    /// <para>
    /// Uses the enum member name rather than the localized action label: labels are full sentences
    /// meant for the action dropdown, whereas a profile name is a short row title — and the built-in
    /// profiles are already named in this style ("ReopenClosed").
    /// </para>
    /// </summary>
    public static string? MigrateLegacyProfileName(string? name)
    {
        if (string.IsNullOrWhiteSpace(name)) return null;
        if (!LegacyChineseNames.TryGetValue(name.Trim(), out var action)) return null;

        var english = action.ToString();
        return string.Equals(name, english, StringComparison.Ordinal) ? null : english;
    }

    /// <summary>
    /// Actions valid for a scope.
    /// <para>
    /// Global scope deliberately excludes the Explorer-specific actions: they would silently do
    /// nothing outside File Explorer.
    /// </para>
    /// </summary>
    public static HotKeyAction[] GetAllowedActions(HotkeyScope scope)
    {
        return scope switch
        {
            HotkeyScope.Global =>
            [
                HotKeyAction.Open,
                HotKeyAction.TabSearch,
                HotKeyAction.ToggleWinHook,
                HotKeyAction.ToggleReuseTabs,
                HotKeyAction.ToggleVisibility,
                HotKeyAction.SnapRight,
                HotKeyAction.SnapLeft,
                HotKeyAction.SnapUp,
                HotKeyAction.SnapDown
            ],
            _ => Enum.GetValues<HotKeyAction>()
        };
    }
}
